### PR TITLE
adding MIT license

### PR DESCRIPTION
**Pull request by RoryO**

### CODE REVIEW

**Review by cobbr2 — DISMISSED** [review]
Looks fine. Do you understand how this will get related back to being the "MIT-LICENSE" by Github / rubygems, etc.,?

**Review by cobbr2 — CHANGES_REQUESTED** [review]
Need to put a license indicator in the .gemspec, too.  Also, I found the new Github trick for adding a license pretty interesting; using it on the qpdf repo so you can review it there. https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by RoryO** [comment]
@cobbr2 Done. Bumped version number for the gem to release with the license after merge.

**Review by cobbr2 — APPROVED** [review]
Looks fine. Obviously, CodeClimate wants a freeze or two on this stuff :)

**Pull request merged**
