### PR TITLE
[# 135280493] Make  schelpper work in warehouse environment

### PR DESCRIPTION
**Pull request by subhenduGR**
Make  schelpper work in warehouse environment

[Tracker #135280493](https://www.pivotaltracker.com/story/show/135280493)
@beghbali @RoryO

### CODE REVIEW

**Comment by RoryO** [comment]
CI has failed for some reason. Can you run tests successfully locally?

**Comment by subhenduGR** [comment]
Well, it works in my local machine

**Comment by RoryO** [comment]
I'll investigate.

**Comment by RoryO** [comment]
I'm going to merge this. I don't know why CI isn't working immediately but tests do work when running locally.

**Comment by richddr** [comment]
Will there be a PR to update the gem for jarvis? @RoryO @subhenduGR

**Comment by RoryO** [comment]
Eff, the version number needed bumped. Sorry I've been terribly scattered lately.

**Pull request merged**
